# Generated by Django 4.2.1 on 2023-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_area_usuario_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='usuario_insercion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
