# Generated by Django 4.2.1 on 2023-06-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_area_area_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_descripcion',
            field=models.CharField(max_length=20),
        ),
    ]
